[project]
org-name = "ballerina"
version = "0.5.0"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "file"
    version = "0.5.0"
    path = "./lib/ballerina-file-0.5.0-java.jar"
    groupId = "ballerina"
    modules = ["file"]

    [[platform.libraries]]
    artifactId = "org.wso2.transport.local-file-system"
    version = "6.0.55"
    path = "./lib/org.wso2.transport.local-file-system-6.0.55.jar"
    groupId = "org.wso2.transport.file"
    modules = ["file"]
