[project]
org-name = "ballerina"
version = "0.0.0"

[platform]
target = "java"

    [[platform.libraries]]
    artafactId = "config-api"
    version = "@project.version@"
    path = "./lib/ballerina-config-api-@project.version@.jar"
    groupId = "ballerina"
    modules = ["config-api"]
