[project]
org-name = "ballerina"
version = "1.0.0"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "config"
    version = "1.0.0"
    path = "./lib/ballerina-config-1.0.0-java.jar"
    groupId = "ballerina"
    modules = ["config-api"]
