[base_command]
name = "init"
short = "Initialize a Ballerina package inside the current directory"

[help]
[help.base]
examples = """
    Initialise a package in the current directory.
        $ bal init
    """
long = """
    Initialize a Ballerina package inside the current directory.

    This command is currently deprecated and will be removed in a future version.
    It is recommended to use `bal new` instead.

    A Ballerina package is a collection of logically-related Ballerina modules that are versioned and shared as a single unit. All modules of the package share the same 'Ballerina.toml' and the 'target' directory.

    The package directory will have the structure below.
        .
        ├── Ballerina.toml
        └── main.bal

    Any directory becomes a Ballerina package if that directory has a 'Ballerina.toml' file. For library packages, it contains the organization name, package name, and the version.
    The package root directory is the default module directory.

    The 'modules' directory contains other non-default Ballerina modules. Use the 'bal add <module-name>' command to create modules.

    The 'target' directory is created during the build process. It is the output directory, which contains the build artifacts.
    """
synopsis = "bal init [<package>]"
