# Copyright (c) 2018, WSO2 Inc. (http://wso2.com) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
  - mysql

script:
- BALLERINA_VERSION=0.976.1-SNAPSHOT
- DISTRIBUTION_NAME=ballerina-platform-$BALLERINA_VERSION
- MYSQL_CONNECTOR_VERSION=mysql-connector-java-5.1.45
- ACTIVEMQ_VERSION=apache-activemq-5.12.0

# Ballerina
- wget https://product-dist.ballerina.io/nightly/$BALLERINA_VERSION/$DISTRIBUTION_NAME.zip
- unzip $DISTRIBUTION_NAME.zip
- export PATH=$PATH:$(pwd)/$DISTRIBUTION_NAME/bin
- ballerina version

# JDBC
- wget http://dev.mysql.com/get/Downloads/Connector-J/$MYSQL_CONNECTOR_VERSION.tar.gz
- tar xvzf $MYSQL_CONNECTOR_VERSION.tar.gz
- mv $MYSQL_CONNECTOR_VERSION/$MYSQL_CONNECTOR_VERSION-bin.jar $DISTRIBUTION_NAME/bre/lib


# ActiveMQ
- wget https://archive.apache.org/dist/activemq/5.12.0/$ACTIVEMQ_VERSION-bin.tar.gz
- tar xvzf $ACTIVEMQ_VERSION-bin.tar.gz
- cp $ACTIVEMQ_VERSION/activemq-all-5.12.0.jar $DISTRIBUTION_NAME/bre/lib
- ./$ACTIVEMQ_VERSION/bin/activemq start

- cd examples

- ballerina init

- ballerina test --exclude-packages proto-to-ballerina,taint-checking,websub-hub-client-sample,websub-remote-hub-sample,jdbc-client,basic-https-listener-client,config-api,local-transactions,secured-service-with-jwt,mysql-client,mutual-ssl,secured-service-with-basic-auth,directory-listener
