# Copyright (c) 2018, WSO2 Inc. (http://wso2.com) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '{build}'
skip_tags: true
clone_depth: 1
image:
- Visual Studio 2017
environment:
  MAVEN_VERSION: 3.5.0
  APPVEYOR: true
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  nodejs_version: "8"
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        Write-Host "Downloading Maven $env:MAVEN_VERSION"
        (new-object System.Net.WebClient).DownloadFile("https://repo1.maven.org/maven2/org/apache/maven/apache-maven/$env:MAVEN_VERSION/apache-maven-$env:MAVEN_VERSION-bin.zip", 'C:\maven-bin.zip')
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - ps: Install-Product node $env:nodejs_version
  - cmd: npm -g install npm@5.6.0
  - cmd: SET M2_HOME=C:\maven\apache-maven-%MAVEN_VERSION%
  - cmd: SET PATH=%M2_HOME%\bin;%JAVA_HOME%\bin;%PATH:C:\Ruby193\bin;=%;
  - cmd: mvn --version
  - cmd: java -version
  - cmd: node --version
  - cmd: npm --version
  - cmd: git submodule update --init --recursive
build_script:
  - SET MAVEN_OPTS="-Xms1024m"
  - gradlew.bat build -x test --info -scan --stacktrace --console=plain --no-daemon
cache:
  - C:\maven\ -> appveyor.yml
  - C:\Users\appveyor\.m2\ -> pom.xml
  - C:\Users\appveyor\.gradle
  - '%APPDATA%\npm-cache'
