jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  timeoutInMinutes: 150
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.12.0'
  - script: |
      sudo ulimit -n 65535
      wget http://www-eu.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
      tar xzf apache-maven-3.5.4-bin.tar.gz
      export PATH=$(pwd)/apache-maven-3.5.4/bin:$PATH
      mvn -v
      mvn clean install
    displayName: 'Ballerina Linux Build'
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  timeoutInMinutes: 150
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.12.0'
  - script: |
      mvn -v
      ./gradlew build jacocoTestReport --info --stacktrace -scan -Dorg.gradle.parallel=false -x :ballerina-h2:test -x :ballerina-task:test -x :ballerina-socket:test -x :ballerina-tools-integration-test:test -x :ballerina-unit-test:test -x :ballerina-integration-test:test -x :plugin-vscode:test
    displayName: 'Ballerina Windows Build'