[project]
org-name = "ballerina"
version = "0.0.0"

[platform]
target = "java"

    [[platform.libraries]]
    artifactId = "jvm"
    version = "@project.version@"
    path = "./lib/ballerina-jvm-@project.version@.jar"
    groupId = "ballerina"
    modules = ["jvm"]

    [[platform.libraries]]
    artifactId = "asm"
    version = "6.2.1"
    path = "./lib/asm-6.2.1.jar"
    groupId = "org.ow2.asm"
    modules = ["jvm"]
