[project]
org-name = "ballerina"
version = "1.0.0"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "log"
    version = "1.0.0"
    path = "./lib/ballerina-log-1.0.0-java.jar"
    groupId = "ballerina"
    modules = ["log-api"]
