[base_command]
name = "asyncapi"
short = "short description of build"
[help]
[help.base]
long = "long description of asyncapi"
examples="""
  # Generate Ballerina source code from the given AsyncAPI contract.
  $ asyncapi -i /path/to/asyncapi.yaml -o /path/to/output
"""
synopsis = "Generate Ballerina source code from the given AsyncAPI contract."

[[base_command.flag]]
name = "input"
shorthand = "i"
default_val = ""
usage = "This is a mandatory input. The listener will be generated according to the given AsyncAPI contract."

[[base_command.flag]]
name = "output"
shorthand = "o"
default_val = ""
usage = "Location of the generated Ballerina source code."