[project]
org-name = "ballerina"
version = "0.0.0"

[platform]
target = "java"

    [[platform.libraries]]
    artafactId = "task"
    version = "@project.version@"
    path = "./lib/ballerina-task-@project.version@.jar"
    groupId = "ballerina"
    modules = ["task"]

    [[platform.libraries]]
    artafactId = "quartz"
    version = "2.3.1"
    path = "./lib/quartz-2.3.0.jar"
    groupId = "org.quartz-scheduler"
    modules = ["task"]

    [[platform.libraries]]
    artafactId = "HikariCP"
    version = "3.3.1"
    path = "./lib/HikariCP-3.3.1.jar"
    groupId = "com.zaxxer"
    modules = ["task"]
