[project]
org-name = "ballerina"
version = "0.6.0"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "system"
    version = "0.6.0"
    path = "./lib/ballerina-system-0.6.0-java.jar"
    groupId = "ballerina"
    modules = ["system"]
