[project]
org-name = "ballerina"
version = "1.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "crypto"
    version = "@project.version@"
    path = "./lib/ballerina-crypto-@project.version@.jar"
    groupId = "ballerina"
    modules = ["crypto"]

    [[platform.libraries]]
    artifactId = "commons-codec"
    version = "1.15"
    path = "./lib/commons-codec-1.15.jar"
    groupId = "commons-codec"
    modules = ["crypto"]
