[project]
org-name = "ballerina"
version = "1.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "crypto"
    version = "1.0.0"
    path = "./lib/ballerina-crypto-1.0.0-java.jar"
    groupId = "ballerina"
    modules = ["crypto"]
