tracers:
  - name: jaeger
    enabled: true
    className: org.ballerina.tracing.extension.jaeger.OpenTracingExtension
    configuration:
      sampler.type: const
      sampler.param: 1
      reporter.log.spans: true
      reporter.hostname: localhost
      reporter.port: 5775
      reporter.flush.interval.ms: 1000
      reporter.max.buffer.spans: 1000