[project]
org-name = "ballerina"
version = "1.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "web-sub"
    version = "@project.version@"
    path = "./lib/ballerina-websub-@project.version@.jar"
    groupId = "ballerina"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "org.wso2.transport.http.netty"
    version = "6.3.54"
    path = "./lib/org.wso2.transport.http.netty-6.3.54.jar"
    groupId = "org.wso2.transport.http"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "netty-transport-native-unix-common"
    version = "4.1.115.Final"
    path = "./lib/netty-transport-native-unix-common-4.1.115.Final.jar"
    groupId = "io.netty"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "netty-common"
    version = "4.1.115.Final"
    path = "./lib/netty-common-4.1.115.Final.jar"
    groupId = "io.netty"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "netty-buffer"
    version = "4.1.115.Final"
    path = "./lib/netty-buffer-4.1.115.Final.jar"
    groupId = "io.netty"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "netty-transport"
    version = "4.1.115.Final"
    path = "./lib/netty-transport-4.1.115.Final.jar"
    groupId = "io.netty"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "netty-resolver"
    version = "4.1.115.Final"
    path = "./lib/netty-resolver-4.1.115.Final.jar"
    groupId = "io.netty"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "netty-handler"
    version = "4.1.115.Final"
    path = "./lib/netty-handler-4.1.115.Final.jar"
    groupId = "io.netty"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "netty-codec-http"
    version = "4.1.115.Final"
    path = "./lib/netty-codec-http-4.1.115.Final.jar"
    groupId = "io.netty"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "netty-codec"
    version = "4.1.115.Final"
    path = "./lib/netty-codec-4.1.115.Final.jar"
    groupId = "io.netty"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "netty-handler-proxy"
    version = "4.1.115.Final"
    path = "./lib/netty-handler-proxy-4.1.115.Final.jar"
    groupId = "io.netty"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "netty-codec-http2"
    version = "4.1.115.Final"
    path = "./lib/netty-codec-http2-4.1.115.Final.jar"
    groupId = "io.netty"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "commons-pool"
    version = "1.5.6.wso2v1"
    path = "./lib/commons-pool-1.5.6.wso2v1.jar"
    groupId = "commons-pool.wso2"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "snakeyaml"
    version = "2.0"
    path = "./lib/snakeyaml-2.0.jar"
    groupId = "org.yaml"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "bcprov-jdk18on"
    version = "1.78.1"
    path = "./lib/bcprov-jdk18on-1.78.1.jar"
    groupId = "org.bouncycastle"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "bcpkix-jdk18on"
    version = "1.78.1"
    path = "./lib/bcpkix-jdk18on-1.78.1.jar"
    groupId = "org.bouncycastle"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "bcutil-jdk18on"
    version = "1.78.1"
    path = "./lib/bcutil-jdk18on-1.78.1.jar"
    groupId = "org.bouncycastle"
    modules = ["web-sub"]
    
    [[platform.libraries]]
    artifactId = "netty-tcnative-classes"
    version = "2.0.65.Final"
    path = "./lib/netty-tcnative-classes-2.0.65.Final.jar"
    groupId = "io.netty"
    modules = ["web-sub"]
    
    [[platform.libraries]]
    artifactId = "netty-tcnative-boringssl-static"
    version = "2.0.65.Final"
    path = "./lib/netty-tcnative-boringssl-static-2.0.65.Final.jar"
    groupId = "io.netty"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "netty-tcnative-boringssl-static::windows-x86_64"
    version = "2.0.65.Final"
    path = "./lib/netty-tcnative-boringssl-static-2.0.65.Final-windows-x86_64.jar"
    groupId = "io.netty"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "netty-tcnative-boringssl-static::linux-aarch_64"
    version = "2.0.65.Final"
    path = "./lib/netty-tcnative-boringssl-static-2.0.65.Final-linux-aarch_64.jar"
    groupId = "io.netty"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "netty-tcnative-boringssl-static::linux-x86_64"
    version = "2.0.65.Final"
    path = "./lib/netty-tcnative-boringssl-static-2.0.65.Final-linux-x86_64.jar"
    groupId = "io.netty"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "netty-tcnative-boringssl-static::osx-aarch_64"
    version = "2.0.65.Final"
    path = "./lib/netty-tcnative-boringssl-static-2.0.65.Final-osx-aarch_64.jar"
    groupId = "io.netty"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "netty-tcnative-boringssl-static::osx-x86_64"
    version = "2.0.65.Final"
    path = "./lib/netty-tcnative-boringssl-static-2.0.65.Final-osx-x86_64.jar"
    groupId = "io.netty"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "broker-core"
    version = "0.970.5"
    path = "./lib/broker-core-0.970.5.jar"
    groupId = "io.ballerina.messaging"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "broker-common"
    version = "0.970.0"
    path = "./lib/broker-common-0.970.0.jar"
    groupId = "io.ballerina.messaging"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "broker-auth"
    version = "0.970.0"
    path = "./lib/broker-auth-0.970.0.jar"
    groupId = "io.ballerina.messaging"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "broker-rest-runner"
    version = "0.970.0"
    path = "./lib/broker-rest-runner-0.970.0.jar"
    groupId = "io.ballerina.messaging"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "broker-coordination"
    version = "0.970.0"
    path = "./lib/broker-coordination-0.970.0.jar"
    groupId = "io.ballerina.messaging"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "org.wso2.carbon.metrics.core"
    version = "2.3.7"
    path = "./lib/org.wso2.carbon.metrics.core-2.3.7.jar"
    groupId = "org.wso2.carbon.metrics"
    modules = ["web-sub"]

    [[platform.libraries]]
    artifactId = "guava"
    version = "19.0"
    path = "./lib/guava-32.1.1-jre.jar"
    groupId = "com.google.guava"
    modules = ["web-sub"]
