[project]
org-name = "ballerina"
version = "0.0.0"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "llvm"
    version = "0.0.0"
    path = "./lib/ballerina-llvm-0.0.0-java.jar"
    groupId = "ballerina"
    modules = ["llvm"]
