[project]
org-name = "ballerina"
version = "0.0.0"

[platform]
target = "java"

    [[platform.libraries]]
    artafactId = "llvm"
    version = "1.0.0-encoding-SNAPSHOT"
    path = "./lib/ballerina-encoding-@project.version@.jar"
    groupId = "ballerina"
    modules = ["encoding"]
