[project]
org-name = "ballerina"
version = "0.5.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "jsonutils"
    version = "@project.version@"
    path = "./lib/ballerina-jsonutils-@project.version@.jar"
    groupId = "ballerina"
    modules = ["jsonutils"]