[package]
org = "ballerina"
name = "observe"
version = "0.9.0"

[[platform.java11.dependency]]
path = "../libs/ballerina-observability-2.0.0-alpha3.jar"
groupId = "ballerina"
artifactId = "observability"
version = "0.9.0"
