[package]
org = "ballerina"
name = "observe"
version = "0.8.0"

[[platform.java11.dependency]]
path = "../libs/ballerina-observability-2.0.0-Preview6-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "observability"
version = "0.8.0"
