[project]
org-name = "ballerina"
version = "0.5.0"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "io"
    version = "0.5.0"
    path = "./lib/ballerina-io-0.5.0-java.jar"
    groupId = "ballerina"
    modules = ["io"]
