[project]
org-name = "ballerina"
version = "0.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "io"
    version = "@project.version@"
    path = "./lib/ballerina-io-@project.version@.jar"
    groupId = "ballerina"
    modules = ["io"]
