[project]
org-name = "ballerina"
version = "1.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "java-nats-streaming"
    version = "2.2.1"
    path = "./lib/java-nats-streaming-2.2.1.jar"
    groupId = "io.nats"
    modules = ["nats"]

    [[platform.libraries]]
    artifactId = "jnats"
    version = "2.6.0"
    path = "./lib/jnats-2.6.0.jar"
    groupId = "io.nats"
    modules = ["nats"]

    [[platform.libraries]]
    artifactId = "protobuf-java"
    version = "3.25.5"
    path = "./lib/protobuf-java-3.25.5.jar"
    groupId = "com.google.protobuf"
    modules = ["nats"]
    
    [[platform.libraries]]
    artifactId = "nats"
    version = "@project.version@"
    path = "./lib/ballerina-nats-@project.version@.jar"
    groupId = "ballerina"
    modules = ["nats"]
