[project]
org-name = "ballerina"
version = "0.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "rabbitmq"
    version = "@project.version@"
    path = "./lib/ballerina-rabbitmq-@project.version@.jar"
    groupId = "ballerina"
    modules = ["rabbitmq"]

    [[platform.libraries]]
    artifactId = "amqp-client"
    version = "5.7.3"
    path = "./lib/amqp-client-5.7.3.jar"
    groupId = "com.rabbitmq"
    modules = ["rabbitmq"]
