[package]
org = "ballerinai"
name = "observe"
version = "0.9.0"

[[platform.java11.dependency]]
path = "../libs/ballerina-observability-internal-2.0.0-alpha3.jar"
groupId = "ballerina"
artifactId = "observability-internal"
version = "0.9.0"
