[project]
org-name = "ballerina"
version = "0.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "jdbc"
    version = "@project.version@"
    path = "./lib/ballerina-jdbc2-@project.version@.jar"
    groupId = "ballerina"
    modules = ["jdbc"]

    [[platform.libraries]]
    artifactId = "jdbc"
    version = "@project.version@"
    path = "./lib/ballerina-sql-@project.version@.jar"
    groupId = "ballerina"
    modules = ["jdbc"]

