[project]
org-name = "ballerina"
version = "1.1.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "kafka"
    version = "@project.version@"
    path = "./lib/ballerina-kafka-@project.version@.jar"
    groupId = "ballerina"
    modules = ["kafka"]

    [[platform.libraries]]
    artifactId = "kafka-clients"
    version = "2.3.1"
    path = "./lib/kafka-clients-2.3.1.jar"
    groupId = "org.apache.kafka"
    modules = ["kafka"]

    [[platform.libraries]]
    artifactId = "kafka_2.11"
    version = "2.3.1"
    path = "./lib/kafka_2.11-2.3.1.jar"
    groupId = "org.apache.kafka"
    modules = ["kafka"]
