[project]
org-name = "ballerina"
version = "2.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "kafka"
    version = "2.0.0"
    path = "./lib/ballerina-kafka-2.0.0-java.jar"
    groupId = "ballerina"
    modules = ["kafka"]

    [[platform.libraries]]
    artifactId = "kafka-clients"
    version = "2.3.1"
    path = "./lib/kafka-clients-2.3.1.jar"
    groupId = "org.apache.kafka"
    modules = ["kafka"]

    [[platform.libraries]]
    artifactId = "kafka_2.11"
    version = "2.3.1"
    path = "./lib/kafka_2.11-2.3.1.jar"
    groupId = "org.apache.kafka"
    modules = ["kafka"]
