[project]
org-name = "ballerina"
version = "0.0.0"

[[platform.libraries]]
artifactId = "org.wso2.transport.local-file-system"
version = "6.0.55"
path = "./lib/org.wso2.transport.local-file-system-6.0.55.jar"
groupId = "org.wso2.transport.file"
modules = ["file"]
