[project]
org-name = "ballerina"
version = "0.5.0"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "transactions"
    version = "0.5.0"
    path = "./lib/ballerina-transactions-0.5.0-java.jar"
    groupId = "ballerina"
    modules = ["transactions"]
