name: Publish Ballerina Snapshot

on:
    push:
      branches:
        - master
    workflow_dispatch:

jobs:
    publish-ballerina-lang:
        name: Build and Publish Ballerina Lang
        runs-on: ubuntu-latest
        if: github.repository_owner == 'ballerina-platform'
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v2

            -   name: Set up JDK 11
                uses: actions/setup-java@v1
                with:
                    java-version: 11

            -   name: Setup Node.js
                uses: actions/setup-node@v1
                with:
                    node-version: '8.x'

            -   name: Initialize Sub Modules
                run: git submodule update --init

            -   name: Build and Publish
                env:
                    NEXUS_USERNAME: ${{ secrets.BALLERINA_BOT_USERNAME }}
                    NEXUS_PASSWORD: ${{ secrets.BALLERINA_BOT_TOKEN }}
                run: |
                    ./gradlew build -x createJavadoc -x test -x check --max-workers=2 --no-daemon
                    ./gradlew publish -PpublishToGithub

            -   name: Trigger Standard Library Module Builds
                run: |
                    echo "Triggering stdlib module builds"
                    curl --request \
                    POST 'https://api.github.com/repos/ballerina-platform/ballerina-standard-library/dispatches' \
                    --header 'Accept: application/vnd.github.v3+json' \
                    --header 'Authorization: Bearer ${{ secrets.BALLERINA_BOT_TOKEN }}' \
                    --header 'Content-Type: application/json' \
                    --data-raw '{
                        "event_type": "ballerina-lang-push"
                    }'
