name: Stdlib Release

on: [workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - with:
                  ref: ballerina-stdlib-build-pipeline-test

            - name: Release Pipeline
              uses: ballerina-platform/ballerina-action@master
              with:
                  args:
                      run release
              env:
                  WORKING_DIR: ./stdlib/release
                  GITHUB_TOKEN: ${{ secrets.BAL_BOT_PAT }}
